services:
  ziplink-db:
    image: postgres:15-alpine
    container_name: ziplink-postgres
    environment:
      POSTGRES_DB: ziplink_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ziplink_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  ziplink-db-test:
    image: postgres:15-alpine
    container_name: ziplink-postgres-test
    environment:
      POSTGRES_DB: ziplink_test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"