spring.application.name=ziplink-api

spring.datasource.url=jdbc:postgresql://localhost:5434/ziplink_db
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.docker.compose.enabled=false