spring.application.name=ziplink-api

# Configurações para Desenvolvimento Local
spring.datasource.url=jdbc:postgresql://localhost:5432/ziplink_db
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true