CREATE TABLE tb_accounts (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                             username VARCHAR(255) NOT NULL,
                             password VARCHAR(255) NOT NULL,
                             role VARCHAR(50),
                             CONSTRAINT pk_tb_accounts PRIMARY KEY (id),
                             CONSTRAINT uc_tb_accounts_username UNIQUE (username)
);